version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    image: server
    container_name: node-server
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    # env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    # environment:  // If Mongo Authorization is need to be enabled
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: DockerFile
    image: client
    container_name: react-client
    command: npm run dev 
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local